services:
  postgres:
    image: postgres:13
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"  # Expose PostgreSQL to your host machine
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
