services:
  postgres:
    image: postgres:13
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"  # Expose PostgreSQL to your host machine
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
